In [1]:
import numpy as np

In [2]:
a = np.array(4)

In [3]:
a

array(4)

In [4]:
a.ndim

0

In [27]:
 #1D tensor = vector  # but total element in vector repesented by TotalElement D vector # 4D vector
# collection of 0D tensor = 1D tensor #collection of scalers= vector #collection of vectors = matrices
# axis =rank = dim
b = np.array([1,2,3,4])

In [28]:
b.ndim

1

In [29]:
c=np.array([[1,2,3,4],[5,6,7,8]])

In [30]:
c.ndim

2

In [31]:
d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [32]:
d.ndim

2

In [39]:
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
#matrix3 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

In [40]:
e = np.array([matrix1,matrix2]) #,matrix3

In [41]:
print(e)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[9 8 7]
  [6 5 4]
  [3 2 1]]]


In [42]:
e.ndim

3

In [43]:
f= np.array([
    [[[1, 2], [3, 4]], [[5, 6], [7, 8]]],
    [[[9, 10], [11, 12]], [[13, 14], [15, 16]]],
    [[[1, 3],[8, 9]],[[5, 4],[2, 1]]]
])

In [44]:
print(f)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]


 [[[ 1  3]
   [ 8  9]]

  [[ 5  4]
   [ 2  1]]]]


In [45]:
f.ndim

4